name: Add User to Repositories

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees que active la acción

jobs:
  add-user:
    runs-on: ubuntu-latest
    inputs:
      username:
        description: 'Nombre de usuario a agregar como colaborador'
        required: true
      permissions:
        description: 'Permisos a asignar al usuario (admin, write, read)'
        required: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add user to repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for repo in $(curl -s "https://api.github.com/users/Bejaranorafael/repos" | grep -o 'git@github.com:[^"]*'); do
            repo_name=$(basename $repo)
            echo "Adding user ${{ inputs.username }} to repository $repo_name with permissions ${{ inputs.permissions }}"
            curl -X PUT \
              -H "Authorization: token $MI_TOKEN" \
              -d "{\"permission\":\"${{ inputs.permissions }}\"}" \
              "https://api.github.com/repos/tu_nombre_de_usuario_github/$repo_name/collaborators/${{ inputs.username }}"
          done
