name: Print GitHub API Response

on:
  push:
    branches:
      - main

jobs:
  print-api-response:
    runs-on: ubuntu-latest
    env:
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Debug curl output
        run: |
          response=$(curl -s -H "Authorization: token $PAT_GITHUB" -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/repos)
          echo "API Response:"
          echo "$response"
