name: Add User to Repositories

on:
  push:
    branches:
      - main

jobs:
  add-user:
    runs-on: ubuntu-latest
    env:
      USERNAME_TO_ADD: 'jorge'
      PERMISSIONS: 'admin'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add user to repositories
        run: |
          repos=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" "https://api.github.com/user/repos?per_page=100" | jq -r '.[].ssh_url')

          for repo in $repos; do
            repo_name=$(basename $repo)
            echo "Repository: $repo_name"

            collaborator_check=$(curl -s -H "Authorization: token ${{ secrets.PAT_GITHUB }}" "https://api.github.com/repos/$repo_name/collaborators/$USERNAME_TO_ADD")

            if [[ $(echo "$collaborator_check" | jq -r '.message') == "Not Found" ]]; then
              response=$(curl -s -o /dev/null -w "%{http_code}" -X PUT \
                -H "Authorization: token ${{ secrets.PAT_GITHUB }}" \
                -d "{\"permission\":\"$PERMISSIONS\"}" \
                "https://api.github.com/repos/$repo_name/collaborators/$USERNAME_TO_ADD")

              if [[ $response -eq 204 ]]; then
                echo "User $USERNAME_TO_ADD added to repository $repo_name successfully."
              else
                echo "Failed to add user $USERNAME_TO_ADD to repository $repo_name (HTTP code $response)."
              fi
            else
              echo "User $USERNAME_TO_ADD is already a collaborator in repository $repo_name. Skipping."
            fi

            echo ""
          done

      env:
        USERNAME_TO_ADD: ${{ secrets.USERNAME_TO_ADD }}
        PERMISSIONS: ${{ secrets.PERMISSIONS }}
