name: Add User to Repositories

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees que active la acción

jobs:
  add-user:
    runs-on: ubuntu-latest
    env:
      USERNAME_TO_ADD: 'jorge'  # Define el nombre de usuario aquí
      PERMISSIONS: 'admin'  # Define los permisos aquí (admin, write, read, etc.)
      GITHUB_TOKEN: ${{ secrets.prueba_script }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add user to repositories
        run: |
          for repo in $(curl -s "https://api.github.com/user/repos" | grep -o 'git@github.com:[^"]*'); do
            repo_name=$(basename $repo)
            echo "Adding user $USERNAME_TO_ADD to repository $repo_name with permissions $PERMISSIONS"
            curl -X PUT \
              -H "Authorization: token $prueba_script" \
              -d "{\"permission\":\"$PERMISSIONS\"}" \
              "https://api.github.com/repos/$GITHUB_REPOSITORY/collaborators/$USERNAME_TO_ADD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
