name:   Prueba de accion agregar usuario

on:
  push:
    branches:
      - main

jobs:
  add-user:
    runs-on: ubuntu-latest
    env:
      USERNAME_TO_ADD: 'jorge'  # Nombre de usuario 
      PERMISSIONS: 'admin'  # (admin, write, read, etc)
      PAT_GITHUB: ${{ secrets.PAT_GITHUB }}

    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Repositorios
        run: |
          repos=$(curl -s -H "Authorization: token $PAT_GITHUB" "https://api.github.com/user/repos" | jq -r '.[].ssh_url')
          for repo in $repos; do
            repo_name=$(basename $repo)
            echo "Repository: $repo_name"
          
            # Verifica si el usuario exite
            collaborator_check=$(curl -s -H "Authorization: token $PAT_GITHUB" "https://api.github.com/repos/$repo_name/collaborators/$USERNAME_TO_ADD")
          
            # agregar si no existe
            if [[ "$(echo "$collaborator_check" | jq -r '.message')" == "Not Found" ]]; then
              # Agrega usuario
              response=$(curl -s -X PUT \
                -H "Authorization: token $PAT_GITHUB" \
                -d "{\"permission\":\"$PERMISSIONS\"}" \
                "https://api.github.com/repos/$repo_name/collaborators/$USERNAME_TO_ADD")

              # funciono?
              if [[ "$(echo "$response" | jq -r '.id')" != "null" ]]; then
                echo "User $USERNAME_TO_ADD added to repository $repo_name successfully."
              else
                echo "Failed to add user $USERNAME_TO_ADD to repository $repo_name."
              fi
            else
              echo "User $USERNAME_TO_ADD is already a collaborator in repository $repo_name. Skipping."
            fi
            
            echo ""
          done

        env:
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
