name: Add User to Repositories

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees que active la acción

jobs:
  add-user:
    runs-on: ubuntu-latest
    inputs:
      username:
        description: 'Nombre de usuario a agregar como colaborador'
        required: true
      permissions:
        description: 'Permisos a asignar al usuario (ej. admin, write, read)'
        default: 'admin'
        required: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add user to repositories
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME_TO_ADD: ${{ inputs.username }}
          PERMISSIONS: ${{ inputs.permissions }}
        run: |
          for repo in $(curl -s "https://api.github.com/orgs/nombreorganizacion/repos" | grep -o 'git@github.com:[^"]*'); do
            repo_name=$(basename $repo)
            echo "Adding user $USERNAME_TO_ADD to repository $repo_name with permissions $PERMISSIONS"
            curl -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -d "{\"permission\":\"$PERMISSIONS\"}" \
              "https://api.github.com/repos/nombreorganizacion/$repo_name/collaborators/$USERNAME_TO_ADD"
          done
