name: Add User to Repositories

on:
  push:
    branches:
      - main  # Cambia esto según la rama que desees que active la acción

jobs:
  add-user:
    runs-on: ubuntu-latest
    env:
      USERNAME_TO_ADD: ${{ github.event.inputs.username }}
      PERMISSIONS: ${{ github.event.inputs.permissions }}
      GITHUB_TOKEN: ${{ secrets.MI_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add user to repositories
        run: |
          # Script para agregar el usuario usando $USERNAME_TO_ADD y $PERMISSIONS
          echo "Adding user $USERNAME_TO_ADD with permissions $PERMISSIONS"
        env:
          GITHUB_TOKEN: ${{ secrets.MI_TOKEN }}
